### ISSUE TITLE
Feb 26: Opportunities to improve the program

### ISSUE THREAD

**Issue by dimitri-rusin** [dimitri-rusin/oll_onemax#7]
- Create or find an implementation of a standardized Q learning algorithm.
- The policy performance plot should feature the number of minibatch updates on the x axis.
- Put either the variance or the confidence interval into the policy performance plot.
- Remove the boxplot.
- Check if the environment properly simulates the original paper's OLL algorithm.
- On the y axis of the policy performance plot, depict the number of function evaluations (FE) rather than the episode length.
- Replace SQLite with PostgreSQL and run the Q learning algorithm on the Sorbonne cluster.

**Comment by ndangtt** [comment]
about the second point, the standard choice in monitoring RL training progress is the to have the x-axis as the number of (training) time steps. The training budget is also defined based on #time steps to ensure a fair comparison among different RL trainings.

**Comment by dimitri-rusin** [comment]
> about the second point, the standard choice in monitoring RL training progress is the to have the x-axis as the number of (training) time steps. The training budget is also defined based on #time steps to ensure a fair comparison among different RL trainings.

Done.

Now we can switch between number of episodes and training time steps: https://screenrec.com/share/3PmlHVxS0b

We can also remove the option to have the number of training episodes in the x axis completely.

**Comment by ndangtt** [comment]
thanks! Another question I have in this case: did you keep track of the number of training time-steps or the number of Q-table updates? The former one is a property obtained from the training environment, while the latter one is specific to Q-learning algorithm. We'd want to use the former one (i.e., the implementation should be separated from the RL algorithm).

**Comment by dimitri-rusin** [comment]
> thanks! Another question I have in this case: did you keep track of the number of training time-steps or the number of Q-table updates? The former one is a property obtained from the training environment, while the latter one is specific to Q-learning algorithm. We'd want to use the former one (i.e., the implementation should be separated from the RL algorithm).

Okay, I've got a confusion here, let's clarify the terms:

* **Environment time step:** This is one time step taken in the gymnasium environment. So, one call to step() corresponds to one time step.
* **Neural network time step:** This is one update of the weights of the neural network. Usually, from a minibatch of input-output pairs.
* **Q table update:** This is one update to the table of Q values.

When you say _training time step_, do you refer to the **step()** call in the environment? Or the neural network time step?

**Comment by ndangtt** [comment]
I meant environment time steps. It's independent of the RL algorithms, and has similar meaning to #solution evaluations in the black-box optimisation setting.
